__default__:
  - ./trackmate.yml

tracking_method: koft
keys:
  - association_threshold
  - flow_std

values:
  - [3.0, 1.0]
  - [5.0, 1.0]
  - [7.0, 1.0]
  - [3.0, 2.0]
  - [5.0, 2.0]
  - [7.0, 2.0]
