__new_key_policy__: pass

__default__:
  - ../detect.yml
  - ../methods/trackmate.yml
  - ../methods/emht.yml
  - ../methods/koft.yml
  - ../methods/zephir.yml

__run__:
  __main__: tracking_src.grid_search_track:main
  __name__: "{tracking_method}/{simulation_name}"
  __output_dir__: experiment_folder/tracking_grid_search/  # True output_dir is output_dir/__name__

seed: 111
data_name: springs
simulation_name: "{data_name}/1.5-50.0/{seed}"

data: $EXPYRUN_CWD/dataset/{simulation_name}
tracking_method: trackmate
keys:
  - linking_max_distance
  - gap_closing_max_distance
  - kalman_search_radius
  - max_frame_gap

values:
  - [3.0, 4.5, 3.0, 5]
  - [5.0, 7.5, 5.0, 5]
  - [7.0, 10.5, 7.0, 5]
  - [10.0, 15.0, 10.0, 5]
  - [3.0, 4.5, 3.0, 3]
  - [5.0, 7.5, 5.0, 3]
  - [7.0, 10.5, 7.0, 3]
  - [10.0, 15.0, 10.0, 3]
  - [5.0, 7.5, 5.0, 7]
  - [7.0, 10.5, 7.0, 7]
  