__default__:
  - ./default.yml

name: springs_3d


simulator:  # Replace motion with springs motion + global drift
  shape: [200, 200, 200]  # 3D (8M pixels instead of 1M in 2D)
  background:
    min_std: 10.0  # Divide background size by two in 3D
    max_std: 30.0
    min_dist: 0.3

  global_motion:
    noise_position: 6.0  # Reduce positional noise as the dims are smaller
    noise_theta: 0.15
  motion:
    motions:
      - shape_variation
      - local_rotation
      - elastic_motion
    elastic_motion:
      grid_step: 30  # Reduce the grid step to sample control points
      noise:
        contraction:
          amplitude: 20.0  # Reduce a bit the amplitude too ~ 3px
