__new_key_policy__: pass

__default__:
  - ./detect.yml
  - ./methods/emht.yml
  - ./methods/trackmate.yml
  - ./methods/koft.yml

__run__:
  __main__: tracking_src.track:main
  __name__: "{simulation_name}"
  __output_dir__: experiment_folder/tracking/  # True output_dir is output_dir/__name__

seed: 111
simulation_name: springs/1.5-50.0/{seed}

data: $EXPYRUN_CWD/dataset/{simulation_name}
tracking_methods:
  - trackmate
  - emht
  - koft
